import ConnectToDatabase from "./Database/database.js"
import { Question } from "./models/mcq.model.js";

const sampleMCQ = [
  {
    topic: "C",
    difficulty: "easy",
    question: "What is C mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "C",
    difficulty: "easy",
    question: "What is C mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "C",
    difficulty: "easy",
    question: "What is C mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "C",
    difficulty: "easy",
    question: "What is C mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "C",
    difficulty: "easy",
    question: "Which keyword is commonly used in C?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "C",
    difficulty: "easy",
    question: "Which of the following is correct about C?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "C",
    difficulty: "easy",
    question: "Which keyword is commonly used in C?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "C",
    difficulty: "easy",
    question: "Which keyword is commonly used in C?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "C",
    difficulty: "easy",
    question: "What is C mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "C",
    difficulty: "easy",
    question: "Which of the following is correct about C?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "C",
    difficulty: "medium",
    question: "Which protocol/feature belongs to C?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "C",
    difficulty: "medium",
    question: "Which concept is NOT part of C?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "C",
    difficulty: "medium",
    question: "What is the time complexity of C operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "C",
    difficulty: "medium",
    question: "Which protocol/feature belongs to C?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "C",
    difficulty: "medium",
    question: "What is the time complexity of C operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "C",
    difficulty: "medium",
    question: "Which concept is NOT part of C?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "C",
    difficulty: "medium",
    question: "Which concept is NOT part of C?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "C",
    difficulty: "medium",
    question: "Which protocol/feature belongs to C?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "C",
    difficulty: "medium",
    question: "Which concept is NOT part of C?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "C",
    difficulty: "medium",
    question: "Which concept is NOT part of C?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "C",
    difficulty: "hard",
    question: "Which of the following statements about C is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "C",
    difficulty: "hard",
    question: "Which of the following statements about C is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "C",
    difficulty: "hard",
    question: "What happens in C when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "C",
    difficulty: "hard",
    question: "Which of the following statements about C is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "C",
    difficulty: "hard",
    question: "What happens in C when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "C",
    difficulty: "hard",
    question: "What happens in C when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "C",
    difficulty: "hard",
    question: "What happens in C when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "C",
    difficulty: "hard",
    question: "What happens in C when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "C",
    difficulty: "hard",
    question: "In C, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "C",
    difficulty: "hard",
    question: "What happens in C when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "C++",
    difficulty: "easy",
    question: "What is C++ mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "C++",
    difficulty: "easy",
    question: "Which of the following is correct about C++?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "C++",
    difficulty: "easy",
    question: "What is C++ mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "C++",
    difficulty: "easy",
    question: "Which of the following is correct about C++?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "C++",
    difficulty: "easy",
    question: "What is C++ mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "C++",
    difficulty: "easy",
    question: "Which keyword is commonly used in C++?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "C++",
    difficulty: "easy",
    question: "Which keyword is commonly used in C++?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "C++",
    difficulty: "easy",
    question: "Which of the following is correct about C++?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "C++",
    difficulty: "easy",
    question: "What is C++ mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "C++",
    difficulty: "easy",
    question: "Which keyword is commonly used in C++?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "C++",
    difficulty: "medium",
    question: "Which protocol/feature belongs to C++?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "C++",
    difficulty: "medium",
    question: "What is the time complexity of C++ operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "C++",
    difficulty: "medium",
    question: "What is the time complexity of C++ operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "C++",
    difficulty: "medium",
    question: "What is the time complexity of C++ operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "C++",
    difficulty: "medium",
    question: "Which concept is NOT part of C++?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "C++",
    difficulty: "medium",
    question: "Which concept is NOT part of C++?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "C++",
    difficulty: "medium",
    question: "Which concept is NOT part of C++?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "C++",
    difficulty: "medium",
    question: "Which protocol/feature belongs to C++?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "C++",
    difficulty: "medium",
    question: "Which concept is NOT part of C++?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "C++",
    difficulty: "medium",
    question: "Which protocol/feature belongs to C++?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "C++",
    difficulty: "hard",
    question: "In C++, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "C++",
    difficulty: "hard",
    question: "In C++, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "C++",
    difficulty: "hard",
    question: "In C++, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "C++",
    difficulty: "hard",
    question: "In C++, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "C++",
    difficulty: "hard",
    question: "What happens in C++ when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "C++",
    difficulty: "hard",
    question: "What happens in C++ when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "C++",
    difficulty: "hard",
    question: "In C++, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "C++",
    difficulty: "hard",
    question: "Which of the following statements about C++ is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "C++",
    difficulty: "hard",
    question: "What happens in C++ when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "C++",
    difficulty: "hard",
    question: "In C++, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "Java",
    difficulty: "easy",
    question: "Which of the following is correct about Java?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "Java",
    difficulty: "easy",
    question: "Which keyword is commonly used in Java?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "Java",
    difficulty: "easy",
    question: "Which of the following is correct about Java?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "Java",
    difficulty: "easy",
    question: "Which of the following is correct about Java?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "Java",
    difficulty: "easy",
    question: "What is Java mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "Java",
    difficulty: "easy",
    question: "Which of the following is correct about Java?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "Java",
    difficulty: "easy",
    question: "Which keyword is commonly used in Java?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "Java",
    difficulty: "easy",
    question: "What is Java mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "Java",
    difficulty: "easy",
    question: "Which keyword is commonly used in Java?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "Java",
    difficulty: "easy",
    question: "Which of the following is correct about Java?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "Java",
    difficulty: "medium",
    question: "Which protocol/feature belongs to Java?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "Java",
    difficulty: "medium",
    question: "What is the time complexity of Java operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "Java",
    difficulty: "medium",
    question: "Which protocol/feature belongs to Java?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "Java",
    difficulty: "medium",
    question: "Which concept is NOT part of Java?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "Java",
    difficulty: "medium",
    question: "Which protocol/feature belongs to Java?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "Java",
    difficulty: "medium",
    question: "Which protocol/feature belongs to Java?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "Java",
    difficulty: "medium",
    question: "Which protocol/feature belongs to Java?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "Java",
    difficulty: "medium",
    question: "Which concept is NOT part of Java?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "Java",
    difficulty: "medium",
    question: "Which concept is NOT part of Java?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "Java",
    difficulty: "medium",
    question: "Which concept is NOT part of Java?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "Java",
    difficulty: "hard",
    question: "Which of the following statements about Java is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "Java",
    difficulty: "hard",
    question: "What happens in Java when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "Java",
    difficulty: "hard",
    question: "Which of the following statements about Java is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "Java",
    difficulty: "hard",
    question: "What happens in Java when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "Java",
    difficulty: "hard",
    question: "Which of the following statements about Java is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "Java",
    difficulty: "hard",
    question: "What happens in Java when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "Java",
    difficulty: "hard",
    question: "In Java, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "Java",
    difficulty: "hard",
    question: "What happens in Java when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "Java",
    difficulty: "hard",
    question: "Which of the following statements about Java is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "Java",
    difficulty: "hard",
    question: "In Java, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "Python",
    difficulty: "easy",
    question: "Which of the following is correct about Python?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "Python",
    difficulty: "easy",
    question: "Which of the following is correct about Python?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "Python",
    difficulty: "easy",
    question: "Which of the following is correct about Python?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "Python",
    difficulty: "easy",
    question: "Which of the following is correct about Python?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "Python",
    difficulty: "easy",
    question: "Which keyword is commonly used in Python?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "Python",
    difficulty: "easy",
    question: "Which of the following is correct about Python?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "Python",
    difficulty: "easy",
    question: "Which of the following is correct about Python?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "Python",
    difficulty: "easy",
    question: "Which keyword is commonly used in Python?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "Python",
    difficulty: "easy",
    question: "Which of the following is correct about Python?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "Python",
    difficulty: "easy",
    question: "Which keyword is commonly used in Python?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "Python",
    difficulty: "medium",
    question: "Which protocol/feature belongs to Python?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "Python",
    difficulty: "medium",
    question: "Which concept is NOT part of Python?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "Python",
    difficulty: "medium",
    question: "Which concept is NOT part of Python?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "Python",
    difficulty: "medium",
    question: "Which protocol/feature belongs to Python?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "Python",
    difficulty: "medium",
    question: "Which protocol/feature belongs to Python?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "Python",
    difficulty: "medium",
    question: "Which protocol/feature belongs to Python?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "Python",
    difficulty: "medium",
    question: "What is the time complexity of Python operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "Python",
    difficulty: "medium",
    question: "What is the time complexity of Python operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "Python",
    difficulty: "medium",
    question: "Which protocol/feature belongs to Python?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "Python",
    difficulty: "medium",
    question: "What is the time complexity of Python operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "Python",
    difficulty: "hard",
    question: "In Python, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "Python",
    difficulty: "hard",
    question: "Which of the following statements about Python is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "Python",
    difficulty: "hard",
    question: "Which of the following statements about Python is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "Python",
    difficulty: "hard",
    question: "In Python, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "Python",
    difficulty: "hard",
    question: "In Python, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "Python",
    difficulty: "hard",
    question: "What happens in Python when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "Python",
    difficulty: "hard",
    question: "What happens in Python when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "Python",
    difficulty: "hard",
    question: "In Python, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "Python",
    difficulty: "hard",
    question: "Which of the following statements about Python is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "Python",
    difficulty: "hard",
    question: "Which of the following statements about Python is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "JavaScript",
    difficulty: "easy",
    question: "What is JavaScript mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "JavaScript",
    difficulty: "easy",
    question: "Which of the following is correct about JavaScript?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "JavaScript",
    difficulty: "easy",
    question: "Which of the following is correct about JavaScript?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "JavaScript",
    difficulty: "easy",
    question: "Which of the following is correct about JavaScript?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "JavaScript",
    difficulty: "easy",
    question: "What is JavaScript mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "JavaScript",
    difficulty: "easy",
    question: "Which keyword is commonly used in JavaScript?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "JavaScript",
    difficulty: "easy",
    question: "What is JavaScript mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "JavaScript",
    difficulty: "easy",
    question: "Which keyword is commonly used in JavaScript?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "JavaScript",
    difficulty: "easy",
    question: "Which keyword is commonly used in JavaScript?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "JavaScript",
    difficulty: "easy",
    question: "Which keyword is commonly used in JavaScript?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "JavaScript",
    difficulty: "medium",
    question: "Which concept is NOT part of JavaScript?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "JavaScript",
    difficulty: "medium",
    question: "Which protocol/feature belongs to JavaScript?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "JavaScript",
    difficulty: "medium",
    question: "Which protocol/feature belongs to JavaScript?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "JavaScript",
    difficulty: "medium",
    question: "What is the time complexity of JavaScript operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "JavaScript",
    difficulty: "medium",
    question: "What is the time complexity of JavaScript operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "JavaScript",
    difficulty: "medium",
    question: "What is the time complexity of JavaScript operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "JavaScript",
    difficulty: "medium",
    question: "What is the time complexity of JavaScript operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "JavaScript",
    difficulty: "medium",
    question: "Which protocol/feature belongs to JavaScript?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "JavaScript",
    difficulty: "medium",
    question: "Which protocol/feature belongs to JavaScript?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "JavaScript",
    difficulty: "medium",
    question: "What is the time complexity of JavaScript operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "JavaScript",
    difficulty: "hard",
    question: "In JavaScript, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "JavaScript",
    difficulty: "hard",
    question: "What happens in JavaScript when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "JavaScript",
    difficulty: "hard",
    question: "Which of the following statements about JavaScript is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "JavaScript",
    difficulty: "hard",
    question: "In JavaScript, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "JavaScript",
    difficulty: "hard",
    question: "In JavaScript, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "JavaScript",
    difficulty: "hard",
    question: "What happens in JavaScript when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "JavaScript",
    difficulty: "hard",
    question: "In JavaScript, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "JavaScript",
    difficulty: "hard",
    question: "Which of the following statements about JavaScript is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "JavaScript",
    difficulty: "hard",
    question: "What happens in JavaScript when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "JavaScript",
    difficulty: "hard",
    question: "In JavaScript, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "Go",
    difficulty: "easy",
    question: "Which keyword is commonly used in Go?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "Go",
    difficulty: "easy",
    question: "What is Go mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "Go",
    difficulty: "easy",
    question: "Which keyword is commonly used in Go?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "Go",
    difficulty: "easy",
    question: "Which keyword is commonly used in Go?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "Go",
    difficulty: "easy",
    question: "What is Go mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "Go",
    difficulty: "easy",
    question: "What is Go mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "Go",
    difficulty: "easy",
    question: "What is Go mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "Go",
    difficulty: "easy",
    question: "Which keyword is commonly used in Go?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "Go",
    difficulty: "easy",
    question: "Which keyword is commonly used in Go?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "Go",
    difficulty: "easy",
    question: "Which keyword is commonly used in Go?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "Go",
    difficulty: "medium",
    question: "What is the time complexity of Go operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "Go",
    difficulty: "medium",
    question: "Which concept is NOT part of Go?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "Go",
    difficulty: "medium",
    question: "Which concept is NOT part of Go?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "Go",
    difficulty: "medium",
    question: "What is the time complexity of Go operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "Go",
    difficulty: "medium",
    question: "Which concept is NOT part of Go?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "Go",
    difficulty: "medium",
    question: "Which concept is NOT part of Go?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "Go",
    difficulty: "medium",
    question: "What is the time complexity of Go operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "Go",
    difficulty: "medium",
    question: "Which concept is NOT part of Go?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "Go",
    difficulty: "medium",
    question: "What is the time complexity of Go operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "Go",
    difficulty: "medium",
    question: "Which concept is NOT part of Go?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "Go",
    difficulty: "hard",
    question: "In Go, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "Go",
    difficulty: "hard",
    question: "In Go, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "Go",
    difficulty: "hard",
    question: "Which of the following statements about Go is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "Go",
    difficulty: "hard",
    question: "In Go, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "Go",
    difficulty: "hard",
    question: "What happens in Go when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "Go",
    difficulty: "hard",
    question: "In Go, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "Go",
    difficulty: "hard",
    question: "What happens in Go when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "Go",
    difficulty: "hard",
    question: "What happens in Go when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "Go",
    difficulty: "hard",
    question: "Which of the following statements about Go is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "Go",
    difficulty: "hard",
    question: "Which of the following statements about Go is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "PHP",
    difficulty: "easy",
    question: "What is PHP mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "PHP",
    difficulty: "easy",
    question: "Which keyword is commonly used in PHP?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "PHP",
    difficulty: "easy",
    question: "What is PHP mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "PHP",
    difficulty: "easy",
    question: "What is PHP mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "PHP",
    difficulty: "easy",
    question: "What is PHP mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "PHP",
    difficulty: "easy",
    question: "Which of the following is correct about PHP?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "PHP",
    difficulty: "easy",
    question: "Which of the following is correct about PHP?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "PHP",
    difficulty: "easy",
    question: "Which keyword is commonly used in PHP?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "PHP",
    difficulty: "easy",
    question: "What is PHP mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "PHP",
    difficulty: "easy",
    question: "Which of the following is correct about PHP?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "PHP",
    difficulty: "medium",
    question: "Which protocol/feature belongs to PHP?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "PHP",
    difficulty: "medium",
    question: "Which protocol/feature belongs to PHP?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "PHP",
    difficulty: "medium",
    question: "What is the time complexity of PHP operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "PHP",
    difficulty: "medium",
    question: "Which concept is NOT part of PHP?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "PHP",
    difficulty: "medium",
    question: "Which concept is NOT part of PHP?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "PHP",
    difficulty: "medium",
    question: "What is the time complexity of PHP operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "PHP",
    difficulty: "medium",
    question: "Which concept is NOT part of PHP?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "PHP",
    difficulty: "medium",
    question: "Which protocol/feature belongs to PHP?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "PHP",
    difficulty: "medium",
    question: "Which concept is NOT part of PHP?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "PHP",
    difficulty: "medium",
    question: "Which concept is NOT part of PHP?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "PHP",
    difficulty: "hard",
    question: "In PHP, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "PHP",
    difficulty: "hard",
    question: "In PHP, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "PHP",
    difficulty: "hard",
    question: "What happens in PHP when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "PHP",
    difficulty: "hard",
    question: "What happens in PHP when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "PHP",
    difficulty: "hard",
    question: "In PHP, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "PHP",
    difficulty: "hard",
    question: "Which of the following statements about PHP is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "PHP",
    difficulty: "hard",
    question: "Which of the following statements about PHP is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "PHP",
    difficulty: "hard",
    question: "What happens in PHP when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "PHP",
    difficulty: "hard",
    question: "What happens in PHP when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "PHP",
    difficulty: "hard",
    question: "In PHP, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "SQL",
    difficulty: "easy",
    question: "What is SQL mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "SQL",
    difficulty: "easy",
    question: "Which of the following is correct about SQL?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "SQL",
    difficulty: "easy",
    question: "Which keyword is commonly used in SQL?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "SQL",
    difficulty: "easy",
    question: "Which keyword is commonly used in SQL?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "SQL",
    difficulty: "easy",
    question: "Which of the following is correct about SQL?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "SQL",
    difficulty: "easy",
    question: "Which of the following is correct about SQL?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "SQL",
    difficulty: "easy",
    question: "Which keyword is commonly used in SQL?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "SQL",
    difficulty: "easy",
    question: "What is SQL mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "SQL",
    difficulty: "easy",
    question: "What is SQL mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "SQL",
    difficulty: "easy",
    question: "What is SQL mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "SQL",
    difficulty: "medium",
    question: "Which protocol/feature belongs to SQL?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "SQL",
    difficulty: "medium",
    question: "Which concept is NOT part of SQL?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "DNS"],
    answer: 3,
  },
  {
    topic: "SQL",
    difficulty: "medium",
    question: "Which protocol/feature belongs to SQL?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "SQL",
    difficulty: "medium",
    question: "Which protocol/feature belongs to SQL?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "SQL",
    difficulty: "medium",
    question: "What is the time complexity of SQL operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "SQL",
    difficulty: "medium",
    question: "What is the time complexity of SQL operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "SQL",
    difficulty: "medium",
    question: "Which protocol/feature belongs to SQL?",
    options: ["TCP", "UDP", "IP", "All of these"],
    answer: 3,
  },
  {
    topic: "SQL",
    difficulty: "medium",
    question: "What is the time complexity of SQL operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "SQL",
    difficulty: "medium",
    question: "What is the time complexity of SQL operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "SQL",
    difficulty: "medium",
    question: "What is the time complexity of SQL operation?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
  },
  {
    topic: "SQL",
    difficulty: "hard",
    question: "Which of the following statements about SQL is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "SQL",
    difficulty: "hard",
    question: "What happens in SQL when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "SQL",
    difficulty: "hard",
    question: "What happens in SQL when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "SQL",
    difficulty: "hard",
    question: "Which of the following statements about SQL is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "SQL",
    difficulty: "hard",
    question: "What happens in SQL when deadlock occurs?",
    options: [
      "Processes wait forever",
      "OS kills process",
      "Memory clears",
      "None",
    ],
    answer: 0,
  },
  {
    topic: "SQL",
    difficulty: "hard",
    question: "In SQL, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "SQL",
    difficulty: "hard",
    question: "Which of the following statements about SQL is FALSE?",
    options: [
      "It is distributed",
      "It is secure",
      "It always uses TCP",
      "It supports concurrency",
    ],
    answer: 2,
  },
  {
    topic: "SQL",
    difficulty: "hard",
    question: "In SQL, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "SQL",
    difficulty: "hard",
    question: "In SQL, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "SQL",
    difficulty: "hard",
    question: "In SQL, which algorithm is used for optimization?",
    options: ["Gradient Descent", "DFS", "BFS", "Round Robin"],
    answer: 0,
  },
  {
    topic: "MongoDB",
    difficulty: "easy",
    question: "Which of the following is correct about MongoDB?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "MongoDB",
    difficulty: "easy",
    question: "What is MongoDB mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "MongoDB",
    difficulty: "easy",
    question: "What is MongoDB mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "MongoDB",
    difficulty: "easy",
    question: "What is MongoDB mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "MongoDB",
    difficulty: "easy",
    question: "What is MongoDB mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "MongoDB",
    difficulty: "easy",
    question: "Which keyword is commonly used in MongoDB?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "MongoDB",
    difficulty: "easy",
    question: "What is MongoDB mainly used for?",
    options: ["System programming", "Web dev", "AI/ML", "All of the above"],
    answer: 3,
  },
  {
    topic: "MongoDB",
    difficulty: "easy",
    question: "Which keyword is commonly used in MongoDB?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
  {
    topic: "MongoDB",
    difficulty: "easy",
    question: "Which of the following is correct about MongoDB?",
    options: ["It is compiled", "It is interpreted", "It is markup", "None"],
    answer: 1,
  },
  {
    topic: "MongoDB",
    difficulty: "easy",
    question: "Which keyword is commonly used in MongoDB?",
    options: ["var", "let", "def", "func"],
    answer: 2,
  },
];


ConnectToDatabase()

const insertIntoDatabase = async () => {
    try {
        const inserted = await Question.insertMany(mcqData);
        if(inserted) {
            console.log("the data have been seccessfully pushed inside the mongo db database");
        } else {
            console.log("There was an error while inserting the data into database");
        }
    } catch (error) {
        console.log(error);
    }
}

insertIntoDatabase();