import ConnectToDatabase from "../Database/database.js";
import { User } from "../models/user.model.js";

const sampleUsers = [
  {
    clerkId: "clrk_001_fake",
    username: "mohit",
    email: "mohit@example.com",
    profilePicture: "https://randomuser.me/api/portraits/men/1.jpg",
    totalBattles: 22,
    totalWins: 14,
    level: 5,
    rank: "Silver",
    title: ["Quick Solver", "Bug Hunter"],
    xp: 150,
    totalXp: 220,
    winStreak: 3,
    currentRating: 1320,
    highestRating: 1400,
  },
  {
    clerkId: "clrk_002_fake",
    username: "khushi",
    email: "khushi@example.com",
    profilePicture: "https://randomuser.me/api/portraits/women/2.jpg",
    totalBattles: 30,
    totalWins: 20,
    level: 6,
    rank: "Gold",
    title: ["Contest Winner"],
    xp: 240,
    totalXp: 300,
    winStreak: 2,
    currentRating: 1500,
    highestRating: 1550,
  },
  {
    clerkId: "clrk_003_fake",
    username: "arjun",
    email: "arjun@example.com",
    profilePicture: "https://randomuser.me/api/portraits/men/3.jpg",
    totalBattles: 10,
    totalWins: 4,
    level: 2,
    rank: "Bronze",
    title: ["New Challenger"],
    xp: 60,
    totalXp: 120,
    winStreak: 1,
    currentRating: 880,
    highestRating: 920,
  },
  {
    clerkId: "clrk_004_fake",
    username: "sneha",
    email: "sneha@example.com",
    profilePicture: "https://randomuser.me/api/portraits/women/4.jpg",
    totalBattles: 50,
    totalWins: 36,
    level: 8,
    rank: "Diamond",
    title: ["Strategist", "Sharp Coder"],
    xp: 700,
    totalXp: 900,
    winStreak: 6,
    currentRating: 1820,
    highestRating: 1850,
  },
  {
    clerkId: "clrk_005_fake",
    username: "rahul",
    email: "rahul@example.com",
    profilePicture: "https://randomuser.me/api/portraits/men/5.jpg",
    totalBattles: 12,
    totalWins: 5,
    level: 3,
    rank: "Bronze",
    title: ["Persistent"],
    xp: 80,
    totalXp: 150,
    winStreak: 1,
    currentRating: 950,
    highestRating: 1000,
  },
  {
    clerkId: "clrk_006_fake",
    username: "anjali",
    email: "anjali@example.com",
    profilePicture: "https://randomuser.me/api/portraits/women/6.jpg",
    totalBattles: 25,
    totalWins: 15,
    level: 5,
    rank: "Silver",
    title: ["Problem Crusher"],
    xp: 200,
    totalXp: 260,
    winStreak: 4,
    currentRating: 1420,
    highestRating: 1480,
  },
  {
    clerkId: "clrk_007_fake",
    username: "karan",
    email: "karan@example.com",
    profilePicture: "https://randomuser.me/api/portraits/men/7.jpg",
    totalBattles: 60,
    totalWins: 45,
    level: 10,
    rank: "Legend",
    title: ["Grandmaster", "Unstoppable"],
    xp: 950,
    totalXp: 1200,
    winStreak: 10,
    currentRating: 2100,
    highestRating: 2150,
  },
  {
    clerkId: "clrk_008_fake",
    username: "priya",
    email: "priya@example.com",
    profilePicture: "https://randomuser.me/api/portraits/women/8.jpg",
    totalBattles: 18,
    totalWins: 11,
    level: 4,
    rank: "Gold",
    title: ["Code Wizard"],
    xp: 160,
    totalXp: 220,
    winStreak: 2,
    currentRating: 1480,
    highestRating: 1500,
  },
  {
    clerkId: "clrk_009_fake",
    username: "vikas",
    email: "vikas@example.com",
    profilePicture: "https://randomuser.me/api/portraits/men/9.jpg",
    totalBattles: 8,
    totalWins: 2,
    level: 2,
    rank: "unRanked",
    title: [],
    xp: 30,
    totalXp: 80,
    winStreak: 0,
    currentRating: 750,
    highestRating: 780,
  },
  {
    clerkId: "clrk_010_fake",
    username: "neha",
    email: "neha@example.com",
    profilePicture: "https://randomuser.me/api/portraits/women/10.jpg",
    totalBattles: 35,
    totalWins: 22,
    level: 7,
    rank: "Platinum",
    title: ["Fast Thinker"],
    xp: 400,
    totalXp: 600,
    winStreak: 3,
    currentRating: 1650,
    highestRating: 1700,
  },
  {
    clerkId: "clrk_011_fake",
    username: "rohit",
    email: "rohit@example.com",
    profilePicture: "https://randomuser.me/api/portraits/men/11.jpg",
    totalBattles: 28,
    totalWins: 18,
    level: 5,
    rank: "Gold",
    title: ["Challenger"],
    xp: 230,
    totalXp: 280,
    winStreak: 2,
    currentRating: 1520,
    highestRating: 1560,
  },
  {
    clerkId: "clrk_012_fake",
    username: "isha",
    email: "isha@example.com",
    profilePicture: "https://randomuser.me/api/portraits/women/12.jpg",
    totalBattles: 45,
    totalWins: 32,
    level: 9,
    rank: "Ace",
    title: ["Elite Coder"],
    xp: 800,
    totalXp: 1000,
    winStreak: 7,
    currentRating: 1900,
    highestRating: 1950,
  },
];
    
    
    ConnectToDatabase();

const insertIntoDatabase = async () => {
  try {
    const inserted = await User.insertMany(sampleUsers);
    if (inserted) {
      console.log(
        "the data have been seccessfully pushed inside the mongo db database"
      );
    } else {
      console.log("There was an error while inserting the data into database");
    }
  } catch (error) {
    console.log(error);
  }
};

insertIntoDatabase();
